### ISSUE TITLE
Style issues: FB Comment section

### ISSUE THREAD

**Issue by freethlua** [freethlua/individualogist-whats-your-archetype#26]
>Please refer to the screenshot below. The spacing on the left of the quiz still exists, and there's also code showing below it. Space is seen on all mobile devices. Code is only visible on iPhone 6 Plus. Browser used is Safari. Let me know if you need any more info on this. Thanks!

>![whatsapp image 2017-07-05 at 2 18 05 pm](https://user-images.githubusercontent.com/19595715/27851381-dbcf8a3e-618c-11e7-84f1-e4de69bf5912.jpeg)

>![whatsapp image 2017-07-05 at 3 22 45 pm](https://user-images.githubusercontent.com/19595715/27853591-e6ae03d2-6195-11e7-937c-dbc18c748e1b.jpeg)

>Above screenshot is display on Chorme in Kindle (tablet equivalent I suppose).

**Comment by zhixinlin** [comment]
Hi Freeth

Please add the following line to display fb comments from newest to oldest:

data-order-by="reverse_time"

And feel free to close this issue whenever you're ready. Thanks!

**Comment by freethlua** [comment]
Fixed.

>data-order-by="reverse_time"

Done

**Comment by wilsonljx** [comment]
Hi Freeth,

I am still seeing this fb comment box issues in my safari. I am using macbook pro.

<img width="1229" alt="screen shot 2017-07-10 at 10 52 15 am" src="https://user-images.githubusercontent.com/29788050/28001276-e949f6ac-655d-11e7-8c75-37a60c3f4fe1.png">

**Comment by wilsonljx** [comment]
Sorry freeth, ignore this message, I am seeing the old link
